apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-view-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs:
  - get
  - list
  - watch
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
