apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/shclub/edu12-4:master 
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prd"
        - name: SPRING_DATASOURCE_USERNAME
          value: "edu"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "caravan"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mariadb://helm-db-mariadb:3306/edu"
        ports:
        - containerPort: 8080
